**1. Import NumPy as np**

In [1]:
import numpy as np
# [Bonus part]
# ---------------
# Setting seeding number
seed_number = 4748

**2. Create an array of 10 zeros**

In [2]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**3. Create an array of 10 ones**

In [3]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**4. Create an array of 10 fives**

In [4]:
fives = ones*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**5. Create an array of the integers from 10 to 50**

In [5]:
arr_10_to_50 = np.arange(10,50+1)
arr_10_to_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**6. Create an array of all the even integers from 10 to 50**

In [6]:
arr_10_to_50_even = arr_10_to_50[arr_10_to_50%2 == 0]
arr_10_to_50_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [7]:
arr_3x3_0_to_8 = np.arange(9).reshape(3,3)
arr_3x3_0_to_8 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [8]:
arr_3x3_I = np.eye(3)
arr_3x3_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Use NumPy to generate a random number between 0 and 1 NOTE: Your result’s
value should be different from the one shown below.**

In [9]:
np.random.rand()

0.15815727288511572

**10. Use NumPy to generate an array of 25 random numbers sampled from a standard
normal distribution NOTE: Your result’s values should be different from the ones
shown below.**

In [10]:
# [Bonus part]
# ---------------
# Initiating seeding
np.random.seed(seed_number) 

rand_normal_dist = np.random.randn(25)
rand_normal_dist

array([-1.23936012, -0.77772429, -0.12467779, -1.50185234,  1.03465729,
       -0.98253213,  0.27899244, -0.91417073,  1.08570574, -0.00836116,
        0.14039756,  1.25083327,  1.27684865,  1.99208471,  0.24501879,
       -0.54449944,  0.67699714,  0.32106698,  0.07027216,  2.2955637 ,
       -1.06411614, -0.13239434, -1.30797458,  0.7109961 , -1.31181333])

**11. Create the following matrix:**
```python
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
[0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
[0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
[0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
[0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
[0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
[0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
[0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
[0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
[0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1. ]])
```

In [11]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**12. Create an array of 20 linearly spaced points between 0 and 1:**

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**0.1 Numpy Indexing and Selection**    
Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate
the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])


**13. Write code that reproduces the output shown below.**
```python
array([[12, 13, 14, 15],
    [17, 18, 19, 20],
    [22, 23, 24, 25]])
```
**⚠Be careful not to run the
cell immediately above the output, otherwise you won’t be able to see the output any
more.**    


In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

**14. Write code that reproduces the output shown below.**    

In [15]:
mat[3][4]

20

**15. Write code that reproduces the output shown below.**    
```python
array([[ 2],
       [ 7],
       [12]])
```

In [16]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

**16. Write code that reproduces the output shown below.**  
```python
array([21, 22, 23, 24, 25])
```

In [17]:
mat[4]

array([21, 22, 23, 24, 25])

**17. Write code that reproduces the output shown below.** 
```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [18]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**0.2 NumPy Operations**    
**18. Get the sum of all the values in mat**     

In [19]:
mat.sum()

325

**19. Get the standard deviation of the values in mat**  

In [20]:
mat.std()

7.211102550927978

**20. Get the sum of all the columns in mat**     

In [21]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

**21. [Bonus] We worked a lot with random data with numpy, but is there a way we can insure that we always
get the same random numbers?**

* Yes. By seeding the random number.
* Called `np.random.seed(seed_number)` line in the question 10, so that Answer 10 will always reproduce same set of random numbers regardless of executing environment

* Tested the code
    * Restarting the Kernel
    * Shutting down the whole book then tried again